---
title: "Strategic Planning"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
runtime: shiny
---

-----------------------------------------------------------------------

# Mission


```{r}

library(reshape2)
library(readxl)
library(dplyr)
library(plotly)
library(shiny)
library(DT)

mission <- read_xlsx('text.xlsx', sheet = 'Mission')
mission <- melt(mission,id.vars = c('Affiliation','Category','Q4: Mission relevant',
                                    'Q5: Mission'))
mission_raw <- mission[complete.cases(mission),]
temp <- mission_raw %>% group_by(value, Affiliation) %>% summarise(n = n())


ui <- fluidPage(
  selectInput('selector',label = "Respondent:", choices = c('All','Student','Faculty','Staff', 'Alumni'), selected = "All",width = '20%'),
  plotlyOutput('chart'),
  dataTableOutput('table')
)

server <- function(input, output,session){
  
mission <- reactive({
  
  if(input$selector == 'All'){
    temp <- temp  %>% group_by(value) %>% summarise(n=sum(n))
    temp$value <- factor(temp$value, levels = unique(temp$value)[order(temp$n, decreasing = FALSE)])
    temp
    
  } else{
    
    temp <- temp[temp$Affiliation == input$selector,]
    temp$value <- factor(temp$value, levels = unique(temp$value)[order(temp$n, decreasing = FALSE)])
    temp
  }
})  

container <- reactive({
  
  if(input$selector == 'All'){
    container <- mission_raw
    container
  } else
  container <- mission_raw[mission_raw$Affiliation == input$selector,]
  container
  
})

output$chart <- renderPlotly({
plot_ly(mission(),x=mission()$n,y=mission()$value,type ='bar') %>% layout(margin = list(l = 200, pad = 4), font=list(size=12))
})

output$table <-renderDataTable({category <- event_data('plotly_click')$y
container()[container()$value==category,c(4,6)]
 
  })
 }
shinyApp(ui, server)

```


# Vision


```{r}

vision <- read_xlsx('text.xlsx', sheet = 'Vision')
vision <- melt(vision,id.vars = c('Q1: Affiliation','Category','Q7: Vision relevant',
                                    'Q11: Vision'))
vision <- vision[complete.cases(vision),]

temp_v <- vision %>% group_by(value) %>% summarise(n = n())
temp2_v <- reorder(temp_v$value, temp_v$n)
  

ui <- fluidPage(
  plotlyOutput('chart2'),
  dataTableOutput('table2')
)

server <- function(input, output,...){
  
output$chart2 <- renderPlotly({
plot_ly(temp_v,x=temp_v$n,y=temp2_v,type='bar') %>% layout(margin = list(l = 200, pad = 4), font=list(size=12))
})

output$table2 <- renderDataTable({
category <- event_data('plotly_click')$y
 if (length(category) == 0){
  # vision[,c(4,6)]
   NULL
 } else {
 datatable(vision[vision$value==category,c(4,6)],escape=1)
 }
  })
}

shinyApp(ui, server)

```


# Core Values


```{r}


values <- read_xlsx('text.xlsx', sheet = 'Values')
values <- melt(values,id.vars = c('Q1: Affiliation','Category','Q10: Relavant',
                                    'Q8: Values'))
values <- values[complete.cases(values),]

temp_vl <- values %>% group_by(value) %>% summarise(n = n())
temp2_vl <- reorder(temp_vl$value, temp_vl$n)


ui <- fluidPage(
  plotlyOutput('chart3'),
  dataTableOutput('table3')
)

server <- function(input, output,...){

output$chart3 <- renderPlotly({
plot_ly(temp_vl,x=temp_vl$n,y=temp2_vl,type='bar') %>% layout(margin = list(l = 200, pad = 4), font=list(size=12))
})

output$table3 <- renderDataTable({
category <- event_data('plotly_click')$y
 if (length(category) == 0){
 #  values[,c(4,6)]
   NULL
 } else {
 datatable(values[values$value==category,c(4,6)],escape = 1)
 }
  })
}

shinyApp(ui, server)

```

